### ISSUE TITLE
about the spatial embedding file

### ISSUE THREAD

**Issue by zLiLong** [LMissher/ST-GRAT#1]
hello，i want to know where i can get the spatial embedding file(suffix is npy)？`parser.add_argument('--SE_file', default='**.npy',
                    help='spatial emebdding file')`

**Comment by LMissher** [comment]
You can use graph embedding algorithms such as node2vec or LINE for the adjacency matrix in the dataset to get the spatial embedding file, the spatial embedding file format is $Nodes\times Features$.
